/*
 * generated by Xtext 2.32.0
 */
package cps.gameoflife


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class LsjatlRuntimeModule extends AbstractLsjatlRuntimeModule {
}
