/*
 * generated by Xtext 2.32.0
 */
package cps.gameoflife


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class LsjatlStandaloneSetup extends LsjatlStandaloneSetupGenerated {

	def static void doSetup() {
		new LsjatlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
