/**
 * generated by Xtext 2.32.0
 */
package cps.gameoflife.validation;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class LsjatlValidator extends AbstractLsjatlValidator {
}
