/**
 * generated by Xtext 2.32.0
 */
package cps.gameoflife.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class LsjatlIdeModule extends AbstractLsjatlIdeModule {
}
