/**
 * generated by Xtext 2.32.0
 */
package cps.gameoflife.lsjatl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cps.gameoflife.lsjatl.Condition#getNCount <em>NCount</em>}</li>
 * </ul>
 *
 * @see cps.gameoflife.lsjatl.LsjatlPackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends EObject
{
  /**
   * Returns the value of the '<em><b>NCount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>NCount</em>' attribute.
   * @see #setNCount(int)
   * @see cps.gameoflife.lsjatl.LsjatlPackage#getCondition_NCount()
   * @model
   * @generated
   */
  int getNCount();

  /**
   * Sets the value of the '{@link cps.gameoflife.lsjatl.Condition#getNCount <em>NCount</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>NCount</em>' attribute.
   * @see #getNCount()
   * @generated
   */
  void setNCount(int value);

} // Condition
