/**
 * generated by Xtext 2.32.0
 */
package cps.gameoflife.lsjatl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Grid Size</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cps.gameoflife.lsjatl.GridSize#getHeight <em>Height</em>}</li>
 *   <li>{@link cps.gameoflife.lsjatl.GridSize#getWidth <em>Width</em>}</li>
 * </ul>
 *
 * @see cps.gameoflife.lsjatl.LsjatlPackage#getGridSize()
 * @model
 * @generated
 */
public interface GridSize extends EObject
{
  /**
   * Returns the value of the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Height</em>' attribute.
   * @see #setHeight(int)
   * @see cps.gameoflife.lsjatl.LsjatlPackage#getGridSize_Height()
   * @model
   * @generated
   */
  int getHeight();

  /**
   * Sets the value of the '{@link cps.gameoflife.lsjatl.GridSize#getHeight <em>Height</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Height</em>' attribute.
   * @see #getHeight()
   * @generated
   */
  void setHeight(int value);

  /**
   * Returns the value of the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Width</em>' attribute.
   * @see #setWidth(int)
   * @see cps.gameoflife.lsjatl.LsjatlPackage#getGridSize_Width()
   * @model
   * @generated
   */
  int getWidth();

  /**
   * Sets the value of the '{@link cps.gameoflife.lsjatl.GridSize#getWidth <em>Width</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Width</em>' attribute.
   * @see #getWidth()
   * @generated
   */
  void setWidth(int value);

} // GridSize
