/**
 * generated by Xtext 2.32.0
 */
package cps.gameoflife.lsjatl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see cps.gameoflife.lsjatl.LsjatlFactory
 * @model kind="package"
 * @generated
 */
public interface LsjatlPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "lsjatl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.gameoflife.cps/Lsjatl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "lsjatl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LsjatlPackage eINSTANCE = cps.gameoflife.lsjatl.impl.LsjatlPackageImpl.init();

  /**
   * The meta object id for the '{@link cps.gameoflife.lsjatl.impl.GameImpl <em>Game</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cps.gameoflife.lsjatl.impl.GameImpl
   * @see cps.gameoflife.lsjatl.impl.LsjatlPackageImpl#getGame()
   * @generated
   */
  int GAME = 0;

  /**
   * The feature id for the '<em><b>Grid</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__GRID = 0;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__RULES = 1;

  /**
   * The number of structural features of the '<em>Game</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link cps.gameoflife.lsjatl.impl.GridImpl <em>Grid</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cps.gameoflife.lsjatl.impl.GridImpl
   * @see cps.gameoflife.lsjatl.impl.LsjatlPackageImpl#getGrid()
   * @generated
   */
  int GRID = 1;

  /**
   * The feature id for the '<em><b>Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID__SIZE = 0;

  /**
   * The feature id for the '<em><b>Populated Cells</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID__POPULATED_CELLS = 1;

  /**
   * The number of structural features of the '<em>Grid</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link cps.gameoflife.lsjatl.impl.GridSizeImpl <em>Grid Size</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cps.gameoflife.lsjatl.impl.GridSizeImpl
   * @see cps.gameoflife.lsjatl.impl.LsjatlPackageImpl#getGridSize()
   * @generated
   */
  int GRID_SIZE = 2;

  /**
   * The feature id for the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID_SIZE__HEIGHT = 0;

  /**
   * The feature id for the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID_SIZE__WIDTH = 1;

  /**
   * The number of structural features of the '<em>Grid Size</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID_SIZE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link cps.gameoflife.lsjatl.impl.PopulatedCellImpl <em>Populated Cell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cps.gameoflife.lsjatl.impl.PopulatedCellImpl
   * @see cps.gameoflife.lsjatl.impl.LsjatlPackageImpl#getPopulatedCell()
   * @generated
   */
  int POPULATED_CELL = 3;

  /**
   * The feature id for the '<em><b>Poi</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POPULATED_CELL__POI = 0;

  /**
   * The number of structural features of the '<em>Populated Cell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POPULATED_CELL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link cps.gameoflife.lsjatl.impl.PointImpl <em>Point</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cps.gameoflife.lsjatl.impl.PointImpl
   * @see cps.gameoflife.lsjatl.impl.LsjatlPackageImpl#getPoint()
   * @generated
   */
  int POINT = 4;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POINT__X = 0;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POINT__Y = 1;

  /**
   * The number of structural features of the '<em>Point</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POINT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link cps.gameoflife.lsjatl.impl.RulesImpl <em>Rules</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cps.gameoflife.lsjatl.impl.RulesImpl
   * @see cps.gameoflife.lsjatl.impl.LsjatlPackageImpl#getRules()
   * @generated
   */
  int RULES = 5;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULES__RULES = 0;

  /**
   * The number of structural features of the '<em>Rules</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link cps.gameoflife.lsjatl.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cps.gameoflife.lsjatl.impl.ConditionImpl
   * @see cps.gameoflife.lsjatl.impl.LsjatlPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 6;

  /**
   * The feature id for the '<em><b>Bool Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__BOOL_OP = 0;

  /**
   * The feature id for the '<em><b>NCount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__NCOUNT = 1;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link cps.gameoflife.lsjatl.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cps.gameoflife.lsjatl.impl.RuleImpl
   * @see cps.gameoflife.lsjatl.impl.LsjatlPackageImpl#getRule()
   * @generated
   */
  int RULE = 7;

  /**
   * The feature id for the '<em><b>State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__STATE = 0;

  /**
   * The feature id for the '<em><b>Conditions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__CONDITIONS = 1;

  /**
   * The feature id for the '<em><b>Result</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__RESULT = 2;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link cps.gameoflife.lsjatl.Game <em>Game</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game</em>'.
   * @see cps.gameoflife.lsjatl.Game
   * @generated
   */
  EClass getGame();

  /**
   * Returns the meta object for the containment reference '{@link cps.gameoflife.lsjatl.Game#getGrid <em>Grid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Grid</em>'.
   * @see cps.gameoflife.lsjatl.Game#getGrid()
   * @see #getGame()
   * @generated
   */
  EReference getGame_Grid();

  /**
   * Returns the meta object for the containment reference '{@link cps.gameoflife.lsjatl.Game#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rules</em>'.
   * @see cps.gameoflife.lsjatl.Game#getRules()
   * @see #getGame()
   * @generated
   */
  EReference getGame_Rules();

  /**
   * Returns the meta object for class '{@link cps.gameoflife.lsjatl.Grid <em>Grid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Grid</em>'.
   * @see cps.gameoflife.lsjatl.Grid
   * @generated
   */
  EClass getGrid();

  /**
   * Returns the meta object for the containment reference '{@link cps.gameoflife.lsjatl.Grid#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Size</em>'.
   * @see cps.gameoflife.lsjatl.Grid#getSize()
   * @see #getGrid()
   * @generated
   */
  EReference getGrid_Size();

  /**
   * Returns the meta object for the containment reference list '{@link cps.gameoflife.lsjatl.Grid#getPopulatedCells <em>Populated Cells</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Populated Cells</em>'.
   * @see cps.gameoflife.lsjatl.Grid#getPopulatedCells()
   * @see #getGrid()
   * @generated
   */
  EReference getGrid_PopulatedCells();

  /**
   * Returns the meta object for class '{@link cps.gameoflife.lsjatl.GridSize <em>Grid Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Grid Size</em>'.
   * @see cps.gameoflife.lsjatl.GridSize
   * @generated
   */
  EClass getGridSize();

  /**
   * Returns the meta object for the attribute '{@link cps.gameoflife.lsjatl.GridSize#getHeight <em>Height</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Height</em>'.
   * @see cps.gameoflife.lsjatl.GridSize#getHeight()
   * @see #getGridSize()
   * @generated
   */
  EAttribute getGridSize_Height();

  /**
   * Returns the meta object for the attribute '{@link cps.gameoflife.lsjatl.GridSize#getWidth <em>Width</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Width</em>'.
   * @see cps.gameoflife.lsjatl.GridSize#getWidth()
   * @see #getGridSize()
   * @generated
   */
  EAttribute getGridSize_Width();

  /**
   * Returns the meta object for class '{@link cps.gameoflife.lsjatl.PopulatedCell <em>Populated Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Populated Cell</em>'.
   * @see cps.gameoflife.lsjatl.PopulatedCell
   * @generated
   */
  EClass getPopulatedCell();

  /**
   * Returns the meta object for the containment reference '{@link cps.gameoflife.lsjatl.PopulatedCell#getPoi <em>Poi</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Poi</em>'.
   * @see cps.gameoflife.lsjatl.PopulatedCell#getPoi()
   * @see #getPopulatedCell()
   * @generated
   */
  EReference getPopulatedCell_Poi();

  /**
   * Returns the meta object for class '{@link cps.gameoflife.lsjatl.Point <em>Point</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Point</em>'.
   * @see cps.gameoflife.lsjatl.Point
   * @generated
   */
  EClass getPoint();

  /**
   * Returns the meta object for the attribute '{@link cps.gameoflife.lsjatl.Point#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see cps.gameoflife.lsjatl.Point#getX()
   * @see #getPoint()
   * @generated
   */
  EAttribute getPoint_X();

  /**
   * Returns the meta object for the attribute '{@link cps.gameoflife.lsjatl.Point#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see cps.gameoflife.lsjatl.Point#getY()
   * @see #getPoint()
   * @generated
   */
  EAttribute getPoint_Y();

  /**
   * Returns the meta object for class '{@link cps.gameoflife.lsjatl.Rules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rules</em>'.
   * @see cps.gameoflife.lsjatl.Rules
   * @generated
   */
  EClass getRules();

  /**
   * Returns the meta object for the containment reference list '{@link cps.gameoflife.lsjatl.Rules#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see cps.gameoflife.lsjatl.Rules#getRules()
   * @see #getRules()
   * @generated
   */
  EReference getRules_Rules();

  /**
   * Returns the meta object for class '{@link cps.gameoflife.lsjatl.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see cps.gameoflife.lsjatl.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for the attribute '{@link cps.gameoflife.lsjatl.Condition#getBoolOp <em>Bool Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bool Op</em>'.
   * @see cps.gameoflife.lsjatl.Condition#getBoolOp()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_BoolOp();

  /**
   * Returns the meta object for the attribute '{@link cps.gameoflife.lsjatl.Condition#getNCount <em>NCount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>NCount</em>'.
   * @see cps.gameoflife.lsjatl.Condition#getNCount()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_NCount();

  /**
   * Returns the meta object for class '{@link cps.gameoflife.lsjatl.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see cps.gameoflife.lsjatl.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the attribute '{@link cps.gameoflife.lsjatl.Rule#getState <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>State</em>'.
   * @see cps.gameoflife.lsjatl.Rule#getState()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_State();

  /**
   * Returns the meta object for the containment reference list '{@link cps.gameoflife.lsjatl.Rule#getConditions <em>Conditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Conditions</em>'.
   * @see cps.gameoflife.lsjatl.Rule#getConditions()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Conditions();

  /**
   * Returns the meta object for the attribute '{@link cps.gameoflife.lsjatl.Rule#getResult <em>Result</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Result</em>'.
   * @see cps.gameoflife.lsjatl.Rule#getResult()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Result();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  LsjatlFactory getLsjatlFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link cps.gameoflife.lsjatl.impl.GameImpl <em>Game</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cps.gameoflife.lsjatl.impl.GameImpl
     * @see cps.gameoflife.lsjatl.impl.LsjatlPackageImpl#getGame()
     * @generated
     */
    EClass GAME = eINSTANCE.getGame();

    /**
     * The meta object literal for the '<em><b>Grid</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__GRID = eINSTANCE.getGame_Grid();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__RULES = eINSTANCE.getGame_Rules();

    /**
     * The meta object literal for the '{@link cps.gameoflife.lsjatl.impl.GridImpl <em>Grid</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cps.gameoflife.lsjatl.impl.GridImpl
     * @see cps.gameoflife.lsjatl.impl.LsjatlPackageImpl#getGrid()
     * @generated
     */
    EClass GRID = eINSTANCE.getGrid();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRID__SIZE = eINSTANCE.getGrid_Size();

    /**
     * The meta object literal for the '<em><b>Populated Cells</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRID__POPULATED_CELLS = eINSTANCE.getGrid_PopulatedCells();

    /**
     * The meta object literal for the '{@link cps.gameoflife.lsjatl.impl.GridSizeImpl <em>Grid Size</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cps.gameoflife.lsjatl.impl.GridSizeImpl
     * @see cps.gameoflife.lsjatl.impl.LsjatlPackageImpl#getGridSize()
     * @generated
     */
    EClass GRID_SIZE = eINSTANCE.getGridSize();

    /**
     * The meta object literal for the '<em><b>Height</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GRID_SIZE__HEIGHT = eINSTANCE.getGridSize_Height();

    /**
     * The meta object literal for the '<em><b>Width</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GRID_SIZE__WIDTH = eINSTANCE.getGridSize_Width();

    /**
     * The meta object literal for the '{@link cps.gameoflife.lsjatl.impl.PopulatedCellImpl <em>Populated Cell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cps.gameoflife.lsjatl.impl.PopulatedCellImpl
     * @see cps.gameoflife.lsjatl.impl.LsjatlPackageImpl#getPopulatedCell()
     * @generated
     */
    EClass POPULATED_CELL = eINSTANCE.getPopulatedCell();

    /**
     * The meta object literal for the '<em><b>Poi</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference POPULATED_CELL__POI = eINSTANCE.getPopulatedCell_Poi();

    /**
     * The meta object literal for the '{@link cps.gameoflife.lsjatl.impl.PointImpl <em>Point</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cps.gameoflife.lsjatl.impl.PointImpl
     * @see cps.gameoflife.lsjatl.impl.LsjatlPackageImpl#getPoint()
     * @generated
     */
    EClass POINT = eINSTANCE.getPoint();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POINT__X = eINSTANCE.getPoint_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POINT__Y = eINSTANCE.getPoint_Y();

    /**
     * The meta object literal for the '{@link cps.gameoflife.lsjatl.impl.RulesImpl <em>Rules</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cps.gameoflife.lsjatl.impl.RulesImpl
     * @see cps.gameoflife.lsjatl.impl.LsjatlPackageImpl#getRules()
     * @generated
     */
    EClass RULES = eINSTANCE.getRules();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULES__RULES = eINSTANCE.getRules_Rules();

    /**
     * The meta object literal for the '{@link cps.gameoflife.lsjatl.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cps.gameoflife.lsjatl.impl.ConditionImpl
     * @see cps.gameoflife.lsjatl.impl.LsjatlPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '<em><b>Bool Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__BOOL_OP = eINSTANCE.getCondition_BoolOp();

    /**
     * The meta object literal for the '<em><b>NCount</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__NCOUNT = eINSTANCE.getCondition_NCount();

    /**
     * The meta object literal for the '{@link cps.gameoflife.lsjatl.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cps.gameoflife.lsjatl.impl.RuleImpl
     * @see cps.gameoflife.lsjatl.impl.LsjatlPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>State</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__STATE = eINSTANCE.getRule_State();

    /**
     * The meta object literal for the '<em><b>Conditions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__CONDITIONS = eINSTANCE.getRule_Conditions();

    /**
     * The meta object literal for the '<em><b>Result</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__RESULT = eINSTANCE.getRule_Result();

  }

} //LsjatlPackage
