/**
 * generated by Xtext 2.32.0
 */
package cps.gameoflife.lsjatl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Populated Cell</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cps.gameoflife.lsjatl.PopulatedCell#getPoi <em>Poi</em>}</li>
 * </ul>
 *
 * @see cps.gameoflife.lsjatl.LsjatlPackage#getPopulatedCell()
 * @model
 * @generated
 */
public interface PopulatedCell extends EObject
{
  /**
   * Returns the value of the '<em><b>Poi</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Poi</em>' containment reference.
   * @see #setPoi(Point)
   * @see cps.gameoflife.lsjatl.LsjatlPackage#getPopulatedCell_Poi()
   * @model containment="true"
   * @generated
   */
  Point getPoi();

  /**
   * Sets the value of the '{@link cps.gameoflife.lsjatl.PopulatedCell#getPoi <em>Poi</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Poi</em>' containment reference.
   * @see #getPoi()
   * @generated
   */
  void setPoi(Point value);

} // PopulatedCell
