/*
 * generated by Xtext 2.32.0
 */
package cps.gameoflife.ui.tests;

import com.google.inject.Injector;
import cps.gameoflife.ui.internal.GameoflifeActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class LsjatlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GameoflifeActivator.getInstance().getInjector("cps.gameoflife.Lsjatl");
	}

}
