/**
 * generated by Xtext 2.32.0
 */
package cps.gameoflife;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class LsjatlStandaloneSetup extends LsjatlStandaloneSetupGenerated {
  public static void doSetup() {
    new LsjatlStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
