/*
 * generated by Xtext 2.32.0
 */
package cps.gameoflife.parser.antlr;

import com.google.inject.Inject;
import cps.gameoflife.parser.antlr.internal.InternalLsjatlParser;
import cps.gameoflife.services.LsjatlGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class LsjatlParser extends AbstractAntlrParser {

	@Inject
	private LsjatlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLsjatlParser createParser(XtextTokenStream stream) {
		return new InternalLsjatlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public LsjatlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LsjatlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
