/**
 * generated by Xtext 2.32.0
 */
package cps.gameoflife.ui.contentassist;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class LsjatlProposalProvider extends AbstractLsjatlProposalProvider {
}
