/*
 * generated by Xtext 2.32.0
 */
package cps.gameoflife.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLsjatlScopeProvider extends DelegatingScopeProvider {
}
