/**
 * generated by Xtext 2.32.0
 */
package cps.gameoflife.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class LsjatlQuickfixProvider extends DefaultQuickfixProvider {
}
