/*
 * generated by Xtext 2.32.0
 */
package cps.gameoflife.ide

import com.google.inject.Guice
import cps.gameoflife.LsjatlRuntimeModule
import cps.gameoflife.LsjatlStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class LsjatlIdeSetup extends LsjatlStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new LsjatlRuntimeModule, new LsjatlIdeModule))
	}
	
}
